apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources:
          requests:         
            cpu: "50m"              
            memory: "128Mi"
          limits:           
            cpu: "500m"     
            memory: "512Mi"
status: {}
